todo list: Interactive list
Innocent259/To-Do-list pull request #4
Opened 2023-04-08 14:52 UTC by Innocent259

In this project I:

1. Added a function that allows a user to edit added items.  For now, it is in prompt I'm planning to fix that soon...
2. Added event listener to the checkbox
3. Implemented a function for the "Clear all completed" button 
4. Stored the updated array of items in local storage, so the user gets the correct list of values after the page reloads.

2023-04-08 15:22 UTC, emmiiorji requested changes
Hi @Innocent259, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/230729216-13d0daf9-f1f8-4bcd-a349-37595242f477.gif'/>
</div>


## Good Highlights✔️

- Task status is updated on marking as completed
- The clear-all-completed button works as expected


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-08 15:22 UTC, emmiiorji commented on src/index.js
> +      // eslint-disable-next-line no-use-before-define
As much as possible, kindly avoid disabling linter checks inline. They represent coding standards you share with your team and most of the time enforce adherence to best coding practices.

2023-04-08 15:22 UTC, emmiiorji commented on src/index.js
>        // eslint-disable-next-line no-use-before-define
As mentioned above and for same reasons, kindly remove disables of linter checks.

2023-04-08 20:07 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @Innocent259 :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following GitHub Flow
✔️ Added Clear Method
✔️ Used Filter Methods (ES6)

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-08 20:07 UTC, HAMMAS-SALEEM commented on src/todoList.js
> +
![image](https://user-images.githubusercontent.com/93039359/230740348-91ea7563-eb12-4ebf-aeae-7a9a7e4039e5.png)

- [ ] It would be nice if you fix the error shown in the image above because I got this error while checking a todo 😨 Kindly fix this error and also it doesn't change any data in your localStorage 🤔
- [ ] Kindly put all the methods in a separate js file which are related to the status updates (completed: true/false) to follow the project requirements 👍

2023-04-08 20:07 UTC, HAMMAS-SALEEM commented on src/todoList.js
> +
- [ ] When i clicked on the clear button then nothing happened 😨 Kindly fix this issue to follow the project requirements 👍

2023-04-08 20:07 UTC, HAMMAS-SALEEM commented on src/theDom.js
> +import {
**[OPTIONAL]**

- [ ] It would be great if you add your own logo (Not Microverse logo) at the top of your readme file to make yourself a brand in the tech industry to catch the eyes of recruiters 👍

2023-04-08 22:47 UTC, Ismailco requested changes
### Hi @Innocent259, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights

✔️ No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-08 22:47 UTC, Ismailco commented on src/index.js
> +  const newDescription = prompt('Enter new description:');
- [ ] As the previous reviewer mentioned kindly make sure to move the methods responsible for the status update into a new file

2023-04-12 15:53 UTC, ShadyShawkat approved these changes
## Hi @Innocent259, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 08:58 UTC, merged